check = [
    { type = "Exclude", id = "STAN-0106", scope = "all" },
    { type = "Exclude", id = "STAN-0206", scope = "all" },
    { type = "Exclude", id = "STAN-0103", scope = "all" },
    { type = "Exclude", id = "STAN-0105", scope = "all" },
    { type = "Exclude", id = "STAN-0101", scope = "all" },
    { type = "Exclude", id = "STAN-0302", scope = "all" },
]
